pipeline {
    environment{
        registry = "leexha/node_demo"
        registyCredential = 'dockerhub'
        dockerImage = ''
    }
    parameters{
        string(defaultValue: 'development', description: '', name: 'ENV_DEPLOY', trim: false)
    }
    agent any
    tools{
        nodejs "node"
    }
    stages {

        stage('Git clone'){
            steps{
                git branch: "${params.ENV_DEPLOY}", url: 'https://github.com/leeadh/node-jenkins-app-example.git'
            }
            
        }
        stage('Installing Node') { 
            steps {
                sh 'npm install' 
            }
        }


        stage ('Building image'){
            steps{
                script{
                    dockerImage = docker.build registry + ":<ENTER YOUR TAG>"
                }
            }

        }


        stage ('Pushing to Docker Hub'){
            steps{
                script{
                    docker.withRegistry('',registyCredential){
                        dockerImage.push()
                    }
                }
            }

        }

    }
}